### PR TITLE
Add Ability to Specify Host List and Credentials

### PR DESCRIPTION
**Pull request by zkhcohen**
Threw this together quickly to satisfy my own requirements.

This is working, but isn't thoroughly tested or refactored.

### CODE REVIEW

**Comment by zkhcohen** [comment]
@lux4rd0 If you could test the standard discovery feature, that would be fantastic. My VLAN setup prevents me from verifying that it still works.

---

EDIT: Looks like I need to add handling for when one of the devices drops off the network. I'm busy the next few days, but I'll try to tackle it soon.

**Comment by lux4rd0** [comment]
Ohhhh! Thanks @zkhcohen - let me take a look at this!! Thanks for the effort!

**Comment by zkhcohen** [comment]
Okay, this should be good to go: device discovery works when a device falls off the network now.

**Comment by lux4rd0** [comment]
The new version should handle host lists and credentials, but I've deviated a little bit from what I had before. I appreciate the PR for this, and I'm happy to see if it works well for you. I will close this PR but certainly leave an issue if the differences aren't working for you.

**Pull request closed without merging**
